"""Build frontend/favicon.svg + favicon.ico + apple-touch-icon.png.

The mark: the "HQ" wordmark shorthand with the Q drawn as a magnifier
(ring + tail). The original source was raster only, so the geometry is
declared here once, in a 512-unit design space, and BOTH the SVG and the
rasters are emitted from it — they cannot drift apart.

Pure stdlib: no Pillow or cairosvg required, so the rasterizer is a small
supersampled scanline renderer over the same primitives the SVG uses.

Usage: .venv/bin/python scripts/make_favicon.py
"""

import struct
import zlib
from pathlib import Path

FRONTEND = Path(__file__).resolve().parents[1] / "src" / "jshq" / "frontend"

DARK = (0x22, 0x1E, 0x18)     # tokens.css --t-bg-elev
ACCENT = (0xD9, 0x66, 0x3F)   # tokens.css --t-accent

ICO_SIZES = (16, 32, 48)
APPLE_SIZE = 180
UNITS = 512.0
SS = 4

# --- geometry (512 design space) --------------------------------------------
H_STEM_W = 48
H_TOP, H_BOT = 131, 360
H_LEFT_X, H_RIGHT_X = 33, 177
H_BAR_TOP, H_BAR_BOT = 222, 270

Q_CX, Q_CY = 357, 247
Q_OUTER, Q_INNER = 120, 62
Q_TAIL = (398, 334, 468, 449)  # x0, y0, x1, y1
Q_TAIL_HALF_W = 28


def in_rect(x, y, x0, y0, x1, y1):
    return x0 <= x <= x1 and y0 <= y <= y1


def in_annulus(x, y, cx, cy, r_out, r_in):
    d2 = (x - cx) ** 2 + (y - cy) ** 2
    return r_in * r_in <= d2 <= r_out * r_out


def in_bar(x, y, x0, y0, x1, y1, half_w):
    """Thick segment with butt (square) ends, like the SVG's stroke-linecap."""
    dx, dy = x1 - x0, y1 - y0
    length2 = dx * dx + dy * dy
    if length2 == 0:
        return False
    t = ((x - x0) * dx + (y - y0) * dy) / length2
    if t < 0 or t > 1:
        return False
    px, py = x0 + t * dx, y0 + t * dy
    return (x - px) ** 2 + (y - py) ** 2 <= half_w * half_w


def sample(x, y):
    if (in_rect(x, y, H_LEFT_X, H_TOP, H_LEFT_X + H_STEM_W, H_BOT)
            or in_rect(x, y, H_RIGHT_X, H_TOP, H_RIGHT_X + H_STEM_W, H_BOT)
            or in_rect(x, y, H_LEFT_X, H_BAR_TOP, H_RIGHT_X + H_STEM_W, H_BAR_BOT)
            or in_annulus(x, y, Q_CX, Q_CY, Q_OUTER, Q_INNER)
            or in_bar(x, y, *Q_TAIL, Q_TAIL_HALF_W)):
        return ACCENT
    return DARK


def render(size):
    scale = UNITS / size
    rows = []
    for py in range(size):
        row = bytearray()
        for px in range(size):
            r = g = b = 0
            for sy in range(SS):
                for sx in range(SS):
                    c = sample((px + (sx + 0.5) / SS) * scale,
                               (py + (sy + 0.5) / SS) * scale)
                    r += c[0]
                    g += c[1]
                    b += c[2]
            n = SS * SS
            row += bytes((round(r / n), round(g / n), round(b / n), 255))
        rows.append(bytes(row))
    return rows


def svg_text():
    hexof = lambda c: "#%02x%02x%02x" % c  # noqa: E731
    ring_r = (Q_OUTER + Q_INNER) / 2
    ring_w = Q_OUTER - Q_INNER
    return f"""<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512" role="img" aria-label="Job Search HQ">
  <!-- Generated by scripts/make_favicon.py: edit the geometry there, not here.
       "HQ" with the Q as a magnifier. Colors are the tokens.css bg-elev and
       accent pair, inlined because a favicon cannot read CSS variables.
       (No double hyphens in this comment: they are illegal in XML, and an
       SVG that fails to parse silently stops rendering as a favicon.) -->
  <rect width="512" height="512" fill="{hexof(DARK)}"/>
  <g fill="{hexof(ACCENT)}">
    <rect x="{H_LEFT_X}" y="{H_TOP}" width="{H_STEM_W}" height="{H_BOT - H_TOP}"/>
    <rect x="{H_RIGHT_X}" y="{H_TOP}" width="{H_STEM_W}" height="{H_BOT - H_TOP}"/>
    <rect x="{H_LEFT_X}" y="{H_BAR_TOP}" width="{H_RIGHT_X + H_STEM_W - H_LEFT_X}" height="{H_BAR_BOT - H_BAR_TOP}"/>
  </g>
  <circle cx="{Q_CX}" cy="{Q_CY}" r="{ring_r:g}" fill="none" stroke="{hexof(ACCENT)}" stroke-width="{ring_w:g}"/>
  <line x1="{Q_TAIL[0]}" y1="{Q_TAIL[1]}" x2="{Q_TAIL[2]}" y2="{Q_TAIL[3]}" stroke="{hexof(ACCENT)}" stroke-width="{Q_TAIL_HALF_W * 2}"/>
</svg>
"""


def png_bytes(size, rows):
    def chunk(tag, data):
        return (struct.pack(">I", len(data)) + tag + data
                + struct.pack(">I", zlib.crc32(tag + data) & 0xFFFFFFFF))

    raw = b"".join(b"\x00" + row for row in rows)
    return (b"\x89PNG\r\n\x1a\n"
            + chunk(b"IHDR", struct.pack(">IIBBBBB", size, size, 8, 6, 0, 0, 0))
            + chunk(b"IDAT", zlib.compress(raw, 9))
            + chunk(b"IEND", b""))


def ico_bytes(images):
    header = struct.pack("<HHH", 0, 1, len(images))
    offset = len(header) + 16 * len(images)
    entries, blobs = b"", b""
    for size, png in images:
        entries += struct.pack("<BBBBHHII", size, size, 0, 0, 1, 32, len(png), offset)
        blobs += png
        offset += len(png)
    return header + entries + blobs


def main():
    (FRONTEND / "favicon.svg").write_text(svg_text(), encoding="utf-8")
    images = [(s, png_bytes(s, render(s))) for s in ICO_SIZES]
    (FRONTEND / "favicon.ico").write_bytes(ico_bytes(images))
    apple = png_bytes(APPLE_SIZE, render(APPLE_SIZE))
    (FRONTEND / "apple-touch-icon.png").write_bytes(apple)
    print(f"favicon.svg + favicon.ico ({', '.join(f'{s}px' for s in ICO_SIZES)}) "
          f"+ apple-touch-icon.png ({APPLE_SIZE}px)")


if __name__ == "__main__":
    main()
